project_id = "synnmssbvwbmlcxfgbwu"

[functions.extract-booking]
verify_jwt = false

[functions.clicksign-webhook]
verify_jwt = false

[functions.polish-transcript]
verify_jwt = false

[functions.bouncie-oauth]
verify_jwt = false

[functions.bouncie-webhook]
verify_jwt = false

[functions.bouncie-devices]
verify_jwt = false

[functions.place-details]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false

[functions.snap-to-roads]
verify_jwt = false



[functions.process-email-queue]
verify_jwt = true
