project_id = "synnmssbvwbmlcxfgbwu"

[functions.extract-booking]
verify_jwt = false

[functions.clicksign-webhook]
verify_jwt = false

[functions.polish-transcript]
verify_jwt = false

[functions.bouncie-oauth]
verify_jwt = false

[functions.bouncie-webhook]
verify_jwt = false
